# .travis.yml
dist: xenial
sudo: false

install:
- wget -0 /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.32.4/hugo_0.32.4_Linux-64bit.deb
- sudo dpk -i hugo *.deb

script:
- hugo

deploy:
- provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    branch: master
